###################################################
# header_postfx_params.py
# This file contains declarations for postfx_params
# DO NOT EDIT THIS FILE!
###################################################

fxf_highhdr        = 0x00000001

